server:
  port: 8081

spring:
  application:
    name: msvc-authentication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/usersdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: msvc-authentication
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka