eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory
          uri: lb://msvc-inventory
          predicates:
            - Path=/api/inventory/**
        - id: products
          uri: lb://msvc-inventory
          predicates:
            - Path=/api/products/**
        - id: stockware
          uri: lb://msvc-inventory
          predicates:
            - Path=/api/stockware/**
        - id: warehouse
          uri: lb://msvc-inventory
          predicates:
            - Path=/api/warehouse/**
        - id: authentication
          uri: lb://msvc-authentication
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true